SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE schedule;
TRUNCATE TABLE rooms;
TRUNCATE TABLE movies;

ALTER TABLE movies AUTO_INCREMENT = 1;
ALTER TABLE rooms AUTO_INCREMENT = 1;
ALTER TABLE schedule AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;
